### ISSUE TITLE
Installation error: "No such member: attributes"

### ISSUE THREAD

**Issue by koutheir** [LucasBullen/redOx#11]
When attempting to install the plugin in Eclipse Oxygen 2, I get the following exception:
```
java.lang.IllegalArgumentException: No such member: attributes
	at org.eclipse.equinox.internal.p2.metadata.ProvidedCapability.getMember(ProvidedCapability.java:85)
	at org.eclipse.equinox.internal.p2.metadata.expression.Member$DynamicMember.invoke(Member.java:47)
	at org.eclipse.equinox.internal.p2.metadata.expression.Member$DynamicMember.evaluate(Member.java:42)
	at org.eclipse.equinox.internal.p2.metadata.expression.Matches.evaluate(Matches.java:36)
	at org.eclipse.equinox.internal.p2.metadata.expression.And.evaluate(And.java:26)
	at org.eclipse.equinox.internal.p2.metadata.expression.Unary.evaluate(Unary.java:42)
	at org.eclipse.equinox.internal.p2.metadata.expression.Exists.evaluate(Exists.java:29)
	at org.eclipse.equinox.internal.p2.metadata.expression.CollectionFilter.evaluate(CollectionFilter.java:58)
	at org.eclipse.equinox.internal.p2.metadata.expression.MatchExpression.evaluate(MatchExpression.java:44)
	at org.eclipse.equinox.p2.query.ExpressionMatchQuery.isMatch(ExpressionMatchQuery.java:86)
	at org.eclipse.equinox.p2.query.ExpressionMatchQuery.perform(ExpressionMatchQuery.java:73)
	at org.eclipse.equinox.p2.query.ExpressionMatchQuery.perform(ExpressionMatchQuery.java:63)
	at org.eclipse.equinox.internal.p2.metadata.index.IndexProvider.query(IndexProvider.java:23)
	at org.eclipse.equinox.internal.p2.metadata.index.IndexProvider.query(IndexProvider.java:32)
	at org.eclipse.equinox.internal.p2.director.Slicer.expandRequirement(Slicer.java:183)
	at org.eclipse.equinox.internal.p2.director.Slicer.processIU(Slicer.java:146)
	at org.eclipse.equinox.internal.p2.director.Slicer.slice(Slicer.java:65)
	at org.eclipse.equinox.internal.p2.director.SimplePlanner.getSolutionFor(SimplePlanner.java:331)
	at org.eclipse.equinox.internal.p2.director.SimplePlanner.getProvisioningPlan(SimplePlanner.java:387)
	at org.eclipse.equinox.internal.p2.operations.PlannerResolutionJob.runModal(PlannerResolutionJob.java:76)
	at org.eclipse.equinox.p2.operations.ProfileChangeOperation.resolveModal(ProfileChangeOperation.java:115)
	at org.eclipse.equinox.internal.p2.ui.dialogs.ProvisioningOperationWizard$2.run(ProvisioningOperationWizard.java:295)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

with session data:
```
eclipse.buildId=4.7.2.M20171130-0510
java.version=1.8.0_144
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.cpp.product
Command-line arguments:  -data file:<home_dir>/eclipse-workspace/ -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.cpp.product
```

This might be related to [Bug 528387](https://bugs.eclipse.org/bugs/show_bug.cgi?id=528387).
 
By the way, installing Eclipse Photon 4.8 (still in beta stage as of now) solves the issue. Still, can you please provide a workaround for people using the stable version of Eclipse?

**Comment by LucasBullen** [comment]
Correct, because I published the plugin from Photon 4.8, it is not backwards compatible. Working on a solution now.

**Comment by LucasBullen** [comment]
Issue fixed by using Eclipse 4.7.2 to release and using older versions of dependants. Download site currently at https://github.com/LucasBullen/redox.github.io.

**Comment by koutheir** [comment]
The link `https://github.com/LucasBullen/redox.github.io` does not work. Eclipse says this is not a valid update site. The link that works is this: `https://raw.githubusercontent.com/LucasBullen/redox.github.io/master/`.

**Comment by LucasBullen** [comment]
Whoops, bad copy paste. Supposed to be https://lucasbullen.github.io/redox.github.io/
